org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
  # check these on https://fabricmc.net/develop
  minecraft_version=1.21-pre2
  yarn_mappings=1.21-pre2+build.2
  loader_version=0.15.11
  fabric_version=0.99.4+1.21

# Mod Properties
  group=com.minelittlepony
  displayname=Sockies
  authors=Sollace
  description=Adds wearable socks to Minecraft

# Publishing
  minecraft_version_range=1.21-pre2
  modrinth_loader_type=fabric
  modrinth_project_id=

# Dependencies
  modmenu_version=11.0.0-beta.1
  minelp_version=4.12.0-beta.2+1.21
  trinkets_version=3.10.0

# TMI Testing
  tmi_type=emi
  emi_version=1.0.29+1.20.4
